# Generated by Django 3.1.4 on 2021-04-26 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_title', models.TextField()),
                ('monster_type', models.TextField()),
                ('monster_stats', models.TextField()),
                ('monster_skills', models.TextField()),
                ('monster_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NonPlayableCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_title', models.TextField()),
                ('npc_type', models.TextField()),
                ('npc_stats', models.TextField()),
                ('npc_skills', models.TextField()),
                ('npc_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.TextField()),
                ('note_body', models.TextField()),
                ('note_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_sheet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('phone_number', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('cheat_sheet', models.TextField()),
                ('custom_rules', models.TextField()),
                ('dm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dmApi.dmuser')),
                ('monsters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dmApi.monster')),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dmApi.note')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dmApi.nonplayablecharacter')),
                ('player_characters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dmApi.playercharacter')),
            ],
        ),
    ]
